alter table portdata add column nearest_diva_port_ids MEDIUMTEXT NOT NULL DEFAULT '' after elevate_engineer;

update portdata set nearest_diva_port_ids = '33' where id=315;
update portdata set nearest_diva_port_ids = '36, 28' where id=314;
update portdata set nearest_diva_port_ids = '51' where id=313;
update portdata set nearest_diva_port_ids = '156' where id=312;
update portdata set nearest_diva_port_ids = '49' where id=311;
update portdata set nearest_diva_port_ids = '36' where id=310;
update portdata set nearest_diva_port_ids = '17, 16' where id=309;
update portdata set nearest_diva_port_ids = '4, 5' where id=308;
update portdata set nearest_diva_port_ids = '97, 5' where id=306;
update portdata set nearest_diva_port_ids = '172' where id=305;
update portdata set nearest_diva_port_ids = '16' where id=304;
update portdata set nearest_diva_port_ids = '80' where id=303;
update portdata set nearest_diva_port_ids = '97, 5' where id=301;
update portdata set nearest_diva_port_ids = '102, 96' where id=300;
update portdata set nearest_diva_port_ids = '100' where id=299;
update portdata set nearest_diva_port_ids = '97' where id=298;
update portdata set nearest_diva_port_ids = '102, 96' where id=297;
update portdata set nearest_diva_port_ids = '97, 5' where id=296;
update portdata set nearest_diva_port_ids = '100' where id=295;
update portdata set nearest_diva_port_ids = '102, 103' where id=294;
update portdata set nearest_diva_port_ids = '66, 67' where id=293;
update portdata set nearest_diva_port_ids = '87' where id=292;
update portdata set nearest_diva_port_ids = '64' where id=291;
update portdata set nearest_diva_port_ids = '55' where id=290;
update portdata set nearest_diva_port_ids = '45' where id=289;
update portdata set nearest_diva_port_ids = '41' where id=287;
update portdata set nearest_diva_port_ids = '55' where id=286;
update portdata set nearest_diva_port_ids = '62' where id=285;
update portdata set nearest_diva_port_ids = '92' where id=284;
update portdata set nearest_diva_port_ids = '68' where id=283;
update portdata set nearest_diva_port_ids = '93, 83' where id=282;
update portdata set nearest_diva_port_ids = '81, 74' where id=281;
update portdata set nearest_diva_port_ids = '95, 73' where id=280;
update portdata set nearest_diva_port_ids = '79' where id=279;
update portdata set nearest_diva_port_ids = '14, 10' where id=278;
update portdata set nearest_diva_port_ids = '81, 74' where id=277;
update portdata set nearest_diva_port_ids = '95, 93' where id=276;
update portdata set nearest_diva_port_ids = '178, 71' where id=275;
update portdata set nearest_diva_port_ids = '81, 74' where id=274;
update portdata set nearest_diva_port_ids = '93, 83' where id=273;
update portdata set nearest_diva_port_ids = '135' where id=272;
update portdata set nearest_diva_port_ids = '127' where id=271;
update portdata set nearest_diva_port_ids = '169' where id=269;
update portdata set nearest_diva_port_ids = '171, 169' where id=268;
update portdata set nearest_diva_port_ids = '174' where id=267;
update portdata set nearest_diva_port_ids = '171, 169' where id=266;
update portdata set nearest_diva_port_ids = '172' where id=264;
update portdata set nearest_diva_port_ids = '170' where id=262;
update portdata set nearest_diva_port_ids = '109' where id=181;

select id, name, diva_Surge_1yr, diva_Surge_10yr, diva_Surge_100yr, diva_Surge_1000yr, diva_Surge_Max, mean_high_high_tide, mean_low_low_tide, storm_surge from portdata where id in (315,314,313,312,311,310,309,308,306,305,304,303,301,300,299,298,297,296,295,294,293,292,291,290,289,287,286,285,284,283,282,281,280,279,278,277,276,275,274,273,272,271,269,268,267,266,264,262,181) order by id desc;

create temporary table temp_a select 0 as id, 0.000 as diva_Surge_1yr, 0.000 as diva_Surge_10yr, 0.000 as diva_Surge_100yr, 0.000 as diva_Surge_1000yr, 0.000 as diva_Surge_Max, 0.000 as storm_surge, 0.000 as mean_high_high_tide, 0.000 as mean_low_low_tide from portdata where id in (0);

insert into temp_a select 315 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (33);
insert into temp_a select 314 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (36, 28);
insert into temp_a select 313 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (51);
insert into temp_a select 312 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (156);
insert into temp_a select 311 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (49);
insert into temp_a select 310 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (36);
insert into temp_a select 309 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (17, 16);
insert into temp_a select 308 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (4,5);
insert into temp_a select 306 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (97, 5);
insert into temp_a select 305 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (172);
insert into temp_a select 304 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (16);
insert into temp_a select 303 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (80);
insert into temp_a select 301 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (97, 5);
insert into temp_a select 300 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (102, 96);
insert into temp_a select 299 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (100);
insert into temp_a select 298 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (97);
insert into temp_a select 297 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (102, 96);
insert into temp_a select 296 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (97, 5);
insert into temp_a select 295 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (100);
insert into temp_a select 294 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (102, 103);
insert into temp_a select 293 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (66, 67);
insert into temp_a select 292 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (87);
insert into temp_a select 291 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (64);
insert into temp_a select 290 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (55);
insert into temp_a select 289 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (45);
insert into temp_a select 287 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (41);
insert into temp_a select 286 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (55);
insert into temp_a select 285 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (62);
insert into temp_a select 284 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (92);
insert into temp_a select 283 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (68);
insert into temp_a select 282 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (93, 83);
insert into temp_a select 281 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (81, 74);
insert into temp_a select 280 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (95, 73);
insert into temp_a select 279 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (79);
insert into temp_a select 278 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (14, 10);
insert into temp_a select 277 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (81, 74);
insert into temp_a select 276 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (95, 93);
insert into temp_a select 275 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (178, 71);
insert into temp_a select 274 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (81, 74);
insert into temp_a select 273 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (93, 83);
insert into temp_a select 272 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (135);
insert into temp_a select 271 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (127);
insert into temp_a select 269 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (169);
insert into temp_a select 268 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (171, 169);
insert into temp_a select 267 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (174);
insert into temp_a select 266 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (171, 169);
insert into temp_a select 264 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (172);
insert into temp_a select 262 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (170);
insert into temp_a select 181 as id, round(avg(diva_Surge_1yr), 3) as diva_Surge_1yr, round(avg(diva_Surge_10yr), 3) as diva_Surge_10yr, round(avg(diva_Surge_100yr), 3) as diva_Surge_100yr, round(avg(diva_Surge_1000yr), 3) as diva_Surge_1000yr, round(avg(diva_Surge_Max), 3) as diva_Surge_Max, round(avg(storm_surge), 3) as storm_surge, round(avg(mean_high_high_tide), 3) as mean_high_high_tide, round(avg(mean_low_low_tide), 3) as mean_low_low_tide from portdata where id in (109);

update portdata p, temp_a t set p.diva_Surge_1yr = round(t.diva_Surge_1yr, 3), p.diva_Surge_10yr = round(t.diva_Surge_10yr, 3), p.diva_Surge_100yr = round(t.diva_Surge_100yr, 3), p.diva_Surge_1000yr = round(t.diva_Surge_1000yr, 3), p.diva_Surge_Max = round(t.diva_Surge_Max, 3), p.storm_surge = round(t.storm_surge, 3), p.mean_high_high_tide = round(t.mean_high_high_tide, 3), p.mean_low_low_tide = round(t.mean_low_low_tide, 3) where t.id = p.id;

drop temporary table temp_a;

update portdata set mean_high_high_tide = round(mean_high_high_tide * 12 * 2.54 / 100, 3), mean_low_low_tide = round(mean_low_low_tide * 12 * 2.54 / 100, 3);


update portdata set region='Asia' where id=315;
update portdata set region='Asia' where id=314;
update portdata set region='Asia' where id=313;
update portdata set region='Asia' where id=312;
update portdata set region='Asia' where id=311;
update portdata set region='Asia' where id=310;
update portdata set region='Africa' where id=309;
update portdata set region='Africa' where id=308;
update portdata set region='Middle East' where id=306;
update portdata set region='South America' where id=305;
update portdata set region='Africa' where id=304;
update portdata set region='Africa' where id=303;
update portdata set region='Africa' where id=301;
update portdata set region='Middle East' where id=300;
update portdata set region='Middle East' where id=299;
update portdata set region='Middle East' where id=298;
update portdata set region='Middle East' where id=297;
update portdata set region='Middle East' where id=296;
update portdata set region='Middle East' where id=295;
update portdata set region='Middle East' where id=294;
update portdata set region='Asia' where id=293;
update portdata set region='Asia' where id=292;
update portdata set region='Asia' where id=291;
update portdata set region='Asia' where id=290;
update portdata set region='Asia' where id=289;
update portdata set region='Asia' where id=287;
update portdata set region='Asia' where id=286;
update portdata set region='Asia' where id=285;
update portdata set region='Asia' where id=284;
update portdata set region='Asia' where id=283;
update portdata set region='Europe' where id=282;
update portdata set region='Europe' where id=281;
update portdata set region='Europe' where id=280;
update portdata set region='Europe' where id=279;
update portdata set region='Europe' where id=278;
update portdata set region='Europe' where id=277;
update portdata set region='Europe' where id=276;
update portdata set region='Europe' where id=275;
update portdata set region='Europe' where id=274;
update portdata set region='Europe' where id=273;
update portdata set region='North America' where id=272;
update portdata set region='North America' where id=271;
update portdata set region='South America' where id=269;
update portdata set region='South America' where id=268;
update portdata set region='North America' where id=267;
update portdata set region='South America' where id=266;
update portdata set region='South America' where id=264;
update portdata set region='South America' where id=262;
update portdata set region='North America' where id=181;
update portdata set region='North America' where id=180;
update portdata set region='North America' where id=179;
update portdata set region='Europe' where id=178;
update portdata set region='South America' where id=177;
update portdata set region='South America' where id=176;
update portdata set region='South America' where id=175;
update portdata set region='South America' where id=174;
update portdata set region='South America' where id=173;
update portdata set region='South America' where id=172;
update portdata set region='South America' where id=171;
update portdata set region='South America' where id=170;
update portdata set region='South America' where id=169;
update portdata set region='South America' where id=168;
update portdata set region='South America' where id=167;
update portdata set region='South America' where id=166;
update portdata set region='South America' where id=165;
update portdata set region='South America' where id=164;
update portdata set region='South America' where id=163;
update portdata set region='South America' where id=162;
update portdata set region='South America' where id=161;
update portdata set region='South America' where id=160;
update portdata set region='South America' where id=159;
update portdata set region='Oceania' where id=158;
update portdata set region='Oceania' where id=157;
update portdata set region='Oceania' where id=156;
update portdata set region='Oceania' where id=155;
update portdata set region='Oceania' where id=154;
update portdata set region='Oceania' where id=153;
update portdata set region='Oceania' where id=152;
update portdata set region='Oceania' where id=151;
update portdata set region='Oceania' where id=150;
update portdata set region='Oceania' where id=149;
update portdata set region='Oceania' where id=148;
update portdata set region='Oceania' where id=147;
update portdata set region='Oceania' where id=146;
update portdata set region='Oceania' where id=145;
update portdata set region='North America' where id=144;
update portdata set region='North America' where id=143;
update portdata set region='North America' where id=142;
update portdata set region='North America' where id=141;
update portdata set region='North America' where id=139;
update portdata set region='North America' where id=138;
update portdata set region='North America' where id=137;
update portdata set region='North America' where id=136;
update portdata set region='North America' where id=135;
update portdata set region='North America' where id=134;
update portdata set region='North America' where id=133;
update portdata set region='North America' where id=132;
update portdata set region='North America' where id=131;
update portdata set region='North America' where id=130;
update portdata set region='North America' where id=129;
update portdata set region='North America' where id=128;
update portdata set region='North America' where id=127;
update portdata set region='North America' where id=125;
update portdata set region='North America' where id=124;
update portdata set region='North America' where id=123;
update portdata set region='North America' where id=122;
update portdata set region='North America' where id=121;
update portdata set region='North America' where id=120;
update portdata set region='North America' where id=119;
update portdata set region='North America' where id=118;
update portdata set region='North America' where id=117;
update portdata set region='North America' where id=116;
update portdata set region='North America' where id=115;
update portdata set region='North America' where id=114;
update portdata set region='North America' where id=113;
update portdata set region='North America' where id=112;
update portdata set region='North America' where id=111;
update portdata set region='North America' where id=110;
update portdata set region='North America' where id=109;
update portdata set region='North America' where id=108;
update portdata set region='North America' where id=107;
update portdata set region='North America' where id=106;
update portdata set region='North America' where id=105;
update portdata set region='North America' where id=104;
update portdata set region='Middle East' where id=103;
update portdata set region='Middle East' where id=102;
update portdata set region='Middle East' where id=101;
update portdata set region='Middle East' where id=100;
update portdata set region='Middle East' where id=99;
update portdata set region='Middle East' where id=98;
update portdata set region='Middle East' where id=97;
update portdata set region='Middle East' where id=96;
update portdata set region='Europe' where id=95;
update portdata set region='Europe' where id=94;
update portdata set region='Europe' where id=93;
update portdata set region='Europe' where id=92;
update portdata set region='Europe' where id=91;
update portdata set region='Europe' where id=90;
update portdata set region='Europe' where id=89;
update portdata set region='Europe' where id=88;
update portdata set region='Europe' where id=87;
update portdata set region='Europe' where id=86;
update portdata set region='Europe' where id=85;
update portdata set region='Europe' where id=84;
update portdata set region='Europe' where id=83;
update portdata set region='Europe' where id=82;
update portdata set region='Europe' where id=81;
update portdata set region='Europe' where id=80;
update portdata set region='Europe' where id=79;
update portdata set region='Europe' where id=78;
update portdata set region='Europe' where id=77;
update portdata set region='Europe' where id=76;
update portdata set region='Europe' where id=75;
update portdata set region='Europe' where id=74;
update portdata set region='Europe' where id=73;
update portdata set region='Europe' where id=72;
update portdata set region='Europe' where id=71;
update portdata set region='Asia' where id=70;
update portdata set region='Asia' where id=69;
update portdata set region='Asia' where id=68;
update portdata set region='Asia' where id=67;
update portdata set region='Asia' where id=66;
update portdata set region='Asia' where id=65;
update portdata set region='Asia' where id=64;
update portdata set region='Asia' where id=63;
update portdata set region='Asia' where id=62;
update portdata set region='Asia' where id=61;
update portdata set region='Asia' where id=60;
update portdata set region='Asia' where id=59;
update portdata set region='Asia' where id=58;
update portdata set region='Asia' where id=57;
update portdata set region='Asia' where id=55;
update portdata set region='Asia' where id=54;
update portdata set region='Asia' where id=51;
update portdata set region='Asia' where id=50;
update portdata set region='Asia' where id=49;
update portdata set region='Asia' where id=48;
update portdata set region='Asia' where id=46;
update portdata set region='Asia' where id=45;
update portdata set region='Asia' where id=44;
update portdata set region='Asia' where id=43;
update portdata set region='Asia' where id=42;
update portdata set region='Asia' where id=41;
update portdata set region='Asia' where id=40;
update portdata set region='Asia' where id=39;
update portdata set region='Asia' where id=38;
update portdata set region='Asia' where id=37;
update portdata set region='Asia' where id=36;
update portdata set region='Asia' where id=35;
update portdata set region='Asia' where id=34;
update portdata set region='Asia' where id=32;
update portdata set region='Asia' where id=31;
update portdata set region='Asia' where id=30;
update portdata set region='Asia' where id=29;
update portdata set region='Asia' where id=28;
update portdata set region='Asia' where id=27;
update portdata set region='Asia' where id=26;
update portdata set region='Asia' where id=25;
update portdata set region='Asia' where id=24;
update portdata set region='Asia' where id=23;
update portdata set region='Asia' where id=22;
update portdata set region='Asia' where id=21;
update portdata set region='Africa' where id=20;
update portdata set region='Africa' where id=19;
update portdata set region='Africa' where id=18;
update portdata set region='Africa' where id=17;
update portdata set region='Africa' where id=16;
update portdata set region='Africa' where id=15;
update portdata set region='Africa' where id=14;
update portdata set region='Africa' where id=13;
update portdata set region='Africa' where id=12;
update portdata set region='Africa' where id=10;
update portdata set region='Africa' where id=9;
update portdata set region='Africa' where id=8;
update portdata set region='Africa' where id=7;
update portdata set region='Africa' where id=6;
update portdata set region='Africa' where id=5;
update portdata set region='Africa' where id=4;
update portdata set region='Africa' where id=3;
update portdata set region='Africa' where id=2;
update portdata set region='Africa' where id=1;


update portdata set storm_surge = CAST(diva_Surge_1000yr as DECIMAL(5,3));
update portdata set storm_surge = CAST(diva_Surge_100yr as DECIMAL(5,3));
